# Generated by Django 5.0.2 on 2024-03-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=100)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('travel', models.DecimalField(decimal_places=1, max_digits=4)),
                ('mileage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('wait', models.DecimalField(decimal_places=1, max_digits=4)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expense ($)')),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
