# Generated by Django 5.0.2 on 2024-03-06 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_keeper', '0004_activity_alter_record_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='record_keeper.activity'),
        ),
    ]
